ADMIN = "ADMIN"
DIRECTOR = "DIRECTOR"
MANAGER = "MANAGER"
CUSTOMER = "CUSTOMER"

USER_ROLES = (
    (ADMIN, ADMIN),
    (DIRECTOR, DIRECTOR),
    (MANAGER, MANAGER),
    (CUSTOMER, CUSTOMER),
)


NOT_ASSIGNED = 'NOT ASSIGNED'
PENDING = 'PENDING'
CANCELED = 'CANCELED'
DONE = 'DONE'

ORDER_STATUSES = (
    (NOT_ASSIGNED, NOT_ASSIGNED),
    (PENDING, PENDING),
    (DONE, DONE)
)
DONT_ENOUGH_MONEY = 'DONT ENOUGH MONEY'
MONEY_ENOUGH = 'MONEY ENOUGH'
AVAILABLE = 'AVAILABLE'
DONT_AVAILABLE = 'DONT AVALABLE'